version: '3'
services:
  mysql_go_lang:
    image: mysql:5.7.21
    container_name: mysql_go_lang
    command: --lower_case_table_names=1 --sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  
